### PR TITLE
MouseSelection fix: Make context current, manage state

### LINKED ISSUE #5784: MouseSelector picking doesn't work for certain types of CSG trees
MouseSelector picking is implemented by modifying preview rendering to render ID colors instead of regular surface colors. The IDs are used to map back to an ID associated with each CSG tree leaf node. By knowing this ID, we can walk the CSG tree and determine what code was responsible for generating the pixel we clicked on.

The following is only tested on macOS:

Picking seems to be very dependent on which object is rendered:
* For primitives, it seems to always work well.
* For simple differences, it never works: `difference() { sphere(10; cube(10); }`
* For slightly more complex models, like Examples/Basics/CSG.scad, it works reasonably well, but breaks completely from certain camera angles.

### PR DESCRIPTION
**Pull request by kintel**
Fixes #5784

### CODE REVIEW

**Comment by kintel** [comment]
@damienmarchal Could you give this a quick spin to see if you can spot any functional issues?

**Comment by kintel** [comment]
> Looks like there a couple of debugging messages left over from previous work:
> 
Thx, have rebased - should be gone now.

File: src/gui/MouseSelector.cc [hunk 1]
```diff
@@ -85,8 +89,11 @@ int MouseSelector::select(const Renderer *renderer, int x, int y) {
 
   // TODO: Ideally, we should make the above configurable and reduce duplicate render code in this function.
 
-  if (x > static_cast<int>(this->view->cam.pixel_width) || x < 0 ||
-      y > static_cast<int>(this->view->cam.pixel_height) || y < 0) {
+  const auto width = this->view->cam.pixel_width;
+  const auto height = this->view->cam.pixel_height;
+
+  if (x >= static_cast<int>(width) || x < 0 ||
+      y >= static_cast<int>(height) || y < 0) {
```
Comment (damienmarchal) [inline src/gui/MouseSelector.cc:96]: I'm not sure to understand the use of auto + static_cast
```suggestion
  const int width = this->view->cam.pixel_width;
  const int height = this->view->cam.pixel_height;

  if (x >= width || x < 0 || y >= height || y < 0) {
```

**Comment by damienmarchal** [comment]
@kintel  I gave it a try and it fix the issue.

**Comment by damienmarchal** [comment]
> > Looks like there a couple of debugging messages left over from previous work:
> 
> Thx, have rebased - should be gone now.

I think the messages are in master not in the PR.

File: src/gui/MouseSelector.cc (hunk 1 above)
Comment (kintel) [reply src/gui/MouseSelector.cc]: Yeah, make sense. Thx.
