### PR TITLE
Don't use the mappedInt signal before Qt-5.15

### LINKED ISSUE #5524: cdc33d4f81 breaks export buttons
**Describe the bug**
When commit cdc33d4f81 is included, file export menu actions and buttons no longer do anything.

It's working OK up until the previous commit (1ad142a441).

**Expected behavior**
Pressing the STL button should pop up a file save dialog.

**Code reproducing the issue**
If applicable, add trimmed down, self-contained code demonstrating the issue.

**Screenshots**

**Environment and Version info (please complete the following information):**
```
System:
  Host: toucan Kernel: 5.15.0-126-generic x86_64 bits: 64 
  Desktop: Xfce 4.16.1 Distro: Ubuntu 20.04.6 LTS (Focal Fossa) 
Machine:
  Type: Laptop System: GIGABYTE product: GB-BSi3-6100 v: 1.x 
  serial: <superuser/root required> 
  Mobo: GIGABYTE model: MKLP3AP-00 v: 1.x serial: <superuser/root required> 
  UEFI [Legacy]: American Megatrends v: F5 date: 01/29/2016 
CPU:
  Topology: Dual Core model: Intel Core i3-6100U bits: 64 type: MT MCP 
  L2 cache: 3072 KiB 
  Speed: 2167 MHz min/max: 400/2300 MHz Core speeds (MHz): 1: 2167 2: 2000 
  3: 2045 4: 1735 
Graphics:
  Device-1: Intel Skylake GT2 [HD Graphics 520] driver: i915 v: kernel 
  Display: x11 server: X.Org 1.20.13 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 520 (SKL GT2) 
  v: 4.6 Mesa 21.2.6 
Audio:
  Device-1: Intel Sunrise Point-LP HD Audio driver: snd_hda_intel 
  Device-2: Logitech HD Pro Webcam C920 type: USB 
  driver: snd-usb-audio,uvcvideo 
  Sound Server: ALSA v: k5.15.0-126-generic 
Network:
  Device-1: Intel Ethernet I219-V driver: e1000e 
  IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full 
  mac: 40:8d:5c:f4:c2:44 
  Device-2: Intel Wireless 3165 driver: iwlwifi 
  IF: wlp1s0 state: down mac: ac:2b:6e:15:50:54 
Drives:
  Local Storage: total: 1.82 TiB used: 1.02 TiB (56.2%) 
  ID-1: /dev/sda vendor: Samsung model: SSD 870 EVO 1TB size: 931.51 GiB 
  ID-2: /dev/sdb type: USB vendor: Western Digital model: WD Elements 2621 
  size: 931.48 GiB 
Partition:
  ID-1: / size: 915.32 GiB used: 291.14 GiB (31.8%) fs: ext4 dev: /dev/sda5 
Sensors:
  System Temperatures: cpu: 42.0 C mobo: 29.8 C 
  Fan Speeds (RPM): N/A 
Info:
  Processes: 271 Uptime: 14d 5h 34m Memory: 15.49 GiB used: 7.18 GiB (46.4%) 
  Shell: bash inxi: 3.0.38 
```

Here's CMakeCache.txt, maybe that's useful?

[CMakeCache.txt](https://github.com/user-attachments/files/18230561/CMakeCache.txt)

### PR DESCRIPTION
**Pull request by kintel**
Fixes #5524

### CODE REVIEW

File: src/gui/MainWindow.cc [hunk 1]
```diff
@@ -403,7 +403,11 @@ MainWindow::MainWindow(const QStringList& filenames)
   connect(autoReloadTimer, SIGNAL(timeout()), this, SLOT(checkAutoReload()));
 
   this->exportformat_mapper = new QSignalMapper(this);
-  connect(this->exportformat_mapper, SIGNAL(mappedInt(int)), this, SLOT(actionExportFileFormat(int))) ;
+#if QT_VERSION >= QT_VERSION_CHECK(5, 15, 0)
+  connect(this->exportformat_mapper, &QSignalMapper::mappedInt, this, &MainWindow::actionExportFileFormat);
+#else
+  connect(this->exportformat_mapper, &QSignalMapper::mapped, this, &MainWindow::actionExportFileFormat);
```
Comment (t-paul) [inline src/gui/MainWindow.cc:409]: Trying to support ancient Ubuntu 20.04 too...
```suggestion
  connect(this->exportformat_mapper, static_cast<void (QSignalMapper::*)(int)>(&QSignalMapper::mapped), this, &MainWindow::actionExportFileFormat);
```
(see https://asmaloney.com/2015/05/code/qsignalmapper-example-revisited/)

**Review by t-paul — APPROVED** [review]
AppImage works (Qt5.15). I guess we merge and validate the Snap build after the auto-build did its job.
