### PR TITLE
Have Reindexer return a const ref instead of a pointer into value array.

### LINKED ISSUE #2965: OpenSCAD crashes on invalid (empty) STL or PNG import
```
$ touch empty.png
$ touch empty.stl
$ echo 'import("empty.stl");' > test.scad
$ openscad --version
OpenSCAD version 2019.05
$ openscad test.scad  # [F6]
/usr/include/c++/9/bits/stl_vector.h:1042: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = Eigen::Matrix<float, 3, 1>; _Alloc = std::allocator<Eigen::Matrix<float, 3, 1> >; std::vector<_Tp, _Alloc>::reference = Eigen::Matrix<float, 3, 1>&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted (core dumped)
[tmp]$ echo 'surface("empty.png");' > test.scad
[tmp]$ openscad test.scad   # [F6]
/usr/include/c++/9/bits/stl_vector.h:1042: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = Eigen::Matrix<float, 3, 1>; _Alloc = std::allocator<Eigen::Matrix<float, 3, 1> >; std::vector<_Tp, _Alloc>::reference = Eigen::Matrix<float, 3, 1>&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted (core dumped)
```

More info incl. backtrace in the downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=1717625

This is Fedora 30, x86_64.
OpenSCAD was built with Eigen 3.3.7.

```
$ rpm -q --requires openscad | grep ^lib
libCGAL.so.13()(64bit)
libGL.so.1()(64bit)
libGLEW.so.2.1()(64bit)
libGLU.so.1()(64bit)
libQt5Core.so.5()(64bit)
libQt5Core.so.5(Qt_5)(64bit)
libQt5Core.so.5(Qt_5.12)(64bit)
libQt5DBus.so.5()(64bit)
libQt5DBus.so.5(Qt_5)(64bit)
libQt5Gamepad.so.5()(64bit)
libQt5Gamepad.so.5(Qt_5)(64bit)
libQt5Gui.so.5()(64bit)
libQt5Gui.so.5(Qt_5)(64bit)
libQt5Multimedia.so.5()(64bit)
libQt5Multimedia.so.5(Qt_5)(64bit)
libQt5Network.so.5()(64bit)
libQt5Network.so.5(Qt_5)(64bit)
libQt5Widgets.so.5()(64bit)
libQt5Widgets.so.5(Qt_5)(64bit)
libX11.so.6()(64bit)
libboost_filesystem.so.1.69.0()(64bit)
libboost_program_options.so.1.69.0()(64bit)
libboost_regex.so.1.69.0()(64bit)
libc.so.6()(64bit)
libc.so.6(GLIBC_2.11)(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.3.4)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libdouble-conversion.so.1()(64bit)
libfontconfig.so.1()(64bit)
libfreetype.so.6()(64bit)
libgcc_s.so.1()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libglib-2.0.so.0()(64bit)
libgmp.so.10()(64bit)
libharfbuzz.so.0()(64bit)
libm.so.6()(64bit)
libm.so.6(GLIBC_2.2.5)(64bit)
libm.so.6(GLIBC_2.29)(64bit)
libmpfr.so.4()(64bit)
libopencsg.so.1()(64bit)
libpolyclipping.so.22()(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
libqscintilla2_qt5.so.15()(64bit)
libstdc++.so.6()(64bit)
libstdc++.so.6(CXXABI_1.3)(64bit)
libstdc++.so.6(CXXABI_1.3.3)(64bit)
libstdc++.so.6(CXXABI_1.3.5)(64bit)
libstdc++.so.6(CXXABI_1.3.7)(64bit)
libstdc++.so.6(GLIBCXX_3.4)(64bit)
libstdc++.so.6(GLIBCXX_3.4.11)(64bit)
libstdc++.so.6(GLIBCXX_3.4.14)(64bit)
libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
libstdc++.so.6(GLIBCXX_3.4.18)(64bit)
libstdc++.so.6(GLIBCXX_3.4.19)(64bit)
libstdc++.so.6(GLIBCXX_3.4.20)(64bit)
libstdc++.so.6(GLIBCXX_3.4.21)(64bit)
libstdc++.so.6(GLIBCXX_3.4.22)(64bit)
libstdc++.so.6(GLIBCXX_3.4.26)(64bit)
libstdc++.so.6(GLIBCXX_3.4.5)(64bit)
libstdc++.so.6(GLIBCXX_3.4.9)(64bit)
libxml2.so.2()(64bit)
libxml2.so.2(LIBXML2_2.4.30)(64bit)
libxml2.so.2(LIBXML2_2.5.0)(64bit)
libxml2.so.2(LIBXML2_2.6.0)(64bit)
libzip.so.5()(64bit)
```

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/75195655-openscad-crashes-on-invalid-empty-stl-or-png-import?utm_campaign=plugin&utm_content=tracker%2F52063&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F52063&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by t-paul**
Should fix #2965

### CODE REVIEW

File: src/export_off.cc [hunk 1]
```diff
@@ -83,7 +83,7 @@ void export_off(const shared_ptr<const Geometry> &geom, std::ostream &output)
 	append_geometry(geom, mesh);
 
 	output << "OFF " << mesh.vertices.size() << " " << mesh.numfaces << " 0\n";
-	const Vector3d *v = mesh.vertices.getArray();
+	const auto v = mesh.vertices.getArray();
```
Comment (kintel) [inline src/export_off.cc]: I'm pretty sure that `const auto v` converts to `const std::vector<Vector3d> v`, causing a copy to be made. `const auto &v` would force a reference to be used. Needs testing though as I'm not 100% sure.

Comment (t-paul) [reply src/export_off.cc]: Argh, really? That's an ugly trap then. I'll try to find out...

Comment (t-paul) [reply src/export_off.cc]: Right, so according to https://isocpp.org/blog/2018/09/quick-q-cpp11-auto-what-if-it-gets-a-constant-reference the const is not really needed, but the  `&`.

File: src/Reindexer.h [hunk 2]
```diff
@@ -4,6 +4,8 @@
 #include <functional>
 #include <vector>
 #include <algorithm>
+#include <boost/range/adaptor/map.hpp>
+#include <boost/range/algorithm/copy.hpp>
```
Comment (kintel) [inline src/Reindexer.h]: Since you didn't end up using those, we don't need to include it.

Comment (t-paul) [reply src/Reindexer.h]: Opps, yes. Do you have an idea how to sort `std::pair<T, int>' by value in a stream? I couldn't find anything so far.

Comment (kintel) [reply src/Reindexer.h]: Since we know that the `int` component is unique and dense, insertion is going to be the best solution.
We can still do a range-based for loop to make it look nicer.

Comment (t-paul) [reply src/Reindexer.h]: Ok, lets go for the range based loop then for now :smile:.

**Comment by hroncok** [comment]
Thanks. Will test on Fedora with this patch.

**Comment by hroncok** [comment]
That works. Thank You.

File: src/export_off.cc (hunk 1 above)
Comment (t-paul) [reply src/export_off.cc]: Heh, Compiler Explorer with binary execution support is just awesome: https://godbolt.org/z/CyxTL_ :)
