### PR TITLE
Make sure to save window state before undocked dock widgets are closed

### LINKED ISSUE #6672: Qt6: Undocked windows status not correctly saved to settings
**Describe the bug**
Windows layout - what's enabled and where it's located - is supposed to be preserved on quit and restored on a new startup.
I've been finding that, somewhat unpredictably, my editor and console windows will be closed on restart.

**To Reproduce**
1. Enable console and editor.
2. Undock them into free-floating windows.
3. Ctrl+Q
4. Restart OpenSCAD
5. Observe what set of windows is opened.

**Expected behavior**
Window configuration at quit is restored on start.

**Environment and Version info (please complete the following information):**
 - OS: Windows 11
 - System: Intel PC 64-bit
 - OpenSCAD Version: 2026.02.13, local MSY2 build

**Library & Graphics card information**
Qt version: 6.10.0

**Additional context**
I suspect that maybe Quit operates by closing each window in sequence to ensure that its contents are saved, and that sometimes that close is persisted.

### PR DESCRIPTION
**Pull request by kintel**
Fixes #6672

### CODE REVIEW

File: src/gui/MainWindow.cc [hunk 1]
```diff
@@ -1517,6 +1517,15 @@ bool MainWindow::event(QEvent *event)
 
 bool MainWindow::eventFilter(QObject *obj, QEvent *event)
 {
+  // OpenSCAD quits by closing all top-level windows. However, the order in which top-level are closed is
+  // not defined by Qt, so we may end up closing undocked dock widgets before we've had a chance to save
+  // the windwos state. This overrides close to proactively save the window state.
+  if (event->type() == QEvent::Close) {
+    if (qobject_cast<Dock *>(obj) && !static_cast<QCloseEvent *>(event)->spontaneous()) {
```
Comment (jordanbrown0) [inline src/gui/MainWindow.cc:1524]: windwos -> window

**Review by jordanbrown0 — COMMENTED** [review]
If you have two undocked windows open, do you get two close events and so save the window state twice (once wrong)?

**Comment by kintel** [comment]
> If you have two undocked windows open, do you get two close events and so save the window state twice (once wrong)?

No, because we remember that we saved the state already in `MainWindow::windowStateSaved`

**Comment by jordanbrown0** [comment]
Yeah, I was just noticing that, sorry.

Might consider changing the name to something like "saveWindowStateOnClose" or "finalSaveWindowState", to avoid somebody thinking that they could call it at other times - since it's once-only.

Is the call from MainWindow::closeEvent really necessary, or will it have already been called from the eventFilter?

**Comment by kintel** [comment]
> 
> Is the call from MainWindow::closeEvent really necessary, or will it have already been called from the eventFilter?

Yes; the eventFilter is just a workaround for dock windows sometimes closing before MainWindow. This should really be dealt with by Qt though (and perhaps will in the future).

**Comment by jordanbrown0** [comment]
My point is that I suspect that the eventFilter will see the MainWindow's close before the MW's event function does, so the event function won't ever have anything to do.

But it shouldn't be a problem.

**Review by jordanbrown0 — APPROVED** [review]

**Comment by kintel** [comment]
> My point is that I suspect that the eventFilter will see the MainWindow's close before the MW's event function does, so the event function won't ever have anything to do.
> 
> But it shouldn't be a problem.

Yeah, but MainWindow isn't of type `Dock`, which is what we check for in the filter.

**Comment by jordanbrown0** [comment]
I'm obviously not paying enough attention.  Sorry, will try to do better.  And thanks for getting on this; it's annoying.
