### PR TITLE
Enables "Ctrl/Cmd-Mouse-wheel zooms text" config option to work  (Preliminary fix for #6368)

### LINKED ISSUE #6368: Cannot disable changing the editor text font size via Ctrl+Mouse-wheel
**Describe the bug**
Changing the editor text font size via **Ctrl**+Mouse-wheel cannot be disabled.

(There is a configuration setting to control this but its value is being ignored.)

**To Reproduce**
1. Enter any text into the editor pane.
2. Click on **Edit** → **Preferences** and select the **Editor** tab.
3. **Ctrl/Cmd-Mouse-wheel zooms text** should be unchecked.
4. With the editor focused hold down **Ctrl** and scroll the mouse wheel.
    Observe that the text size changes.

**Expected behavior**

**Ctrl**+Mouse-wheel should not change text size.

**Environment and Version info (please complete the following information):**
 - OS: Ubuntu 22.04
 - System: x86_64
 - OpenSCAD Version 2025.11.16, built from Git [[9ed115a](https://github.com/openscad/openscad/commit/9ed115a534e7ff381da9f789b08b6740ac614ea2)]

**Additional context**
 
This does not appear to be a regression as the same occurs with version 2021.01.

### PR DESCRIPTION
**Pull request by Alex-Kent**
* Optionally filters out **Ctrl**+scroll events in `ScintillaEditor::eventFilter` thus allowing the **Editor**→**Ctrl/Cmd-Mouse-wheel zooms text** preferences setting to function.
* Dikes out superfluous `zoomIn()` and `zoomOut()` calls in `EditorInterface::wheelEvent`

Resolves #6368 (Preliminary fix)

### CODE REVIEW

File: src/gui/Editor.cc [hunk 1]
```diff
@@ -9,8 +9,11 @@ void EditorInterface::wheelEvent(QWheelEvent *event)
...
   if ((event->modifiers() == Qt::ControlModifier) && wheelzoom_enabled) {
-    if (event->angleDelta().y() > 0) zoomIn();
-    else if (event->angleDelta().y() < 0) zoomOut();
+    // Zooming is already being handled internally by QScintilla/Scintilla/Qt.
+    // Having the zoomIn() and zoomOut() calls here appears to simply double the
+    // amount of zoom applied.
+//    if (event->angleDelta().y() > 0) zoomIn();
+//    else if (event->angleDelta().y() < 0) zoomOut();
   } else {
     QWidget::wheelEvent(event);
```
Comment (jordanbrown0) [inline src/gui/Editor.cc]: I think you can remove this function in its entirety, and that you should definitely remove everything but the call to `QWidget::wheelEvent()`.

**Review by jordanbrown0 — CHANGES_REQUESTED** [review]

File: src/gui/Editor.cc (hunk 1 above)
Comment (Alex-Kent) [reply src/gui/Editor.cc]: > remove everything but the call to `QWidget::wheelEvent()`.

Is even that needed?  AFAICT it's redundant as QScintilla already calls that (implicitly or otherwise) when appropriate.  Testing shows that the code appears to run fine with the entire `EditorInterface::wheelEvent` method removed.

Comment (jordanbrown0) [reply src/gui/Editor.cc]: I did say that I thought you could remove it in its entirety.  But if for some reason you can't, at least remove the other stuff.

Comment (Alex-Kent) [reply src/gui/Editor.cc]: I removed the method in its entirety, *cf.* latest push.

Comment (Alex-Kent) [reply src/gui/Editor.cc]: The status is still showing as "Changes requested".  I've both pushed an update and marking this conversation as resolved; is there anything else I need to do?

Comment (jordanbrown0) [reply src/gui/Editor.cc]: Sorry, I didn't properly understand my role in the GitHub review cycle.
