### PR TITLE
Connect preferences after OpenSCADApp has finished initializing

### LINKED ISSUE #6528: OpenSCAD.conf now in "Unknown Organization" dir instead of "OpenSCAD"
**Describe the bug**
The OpenSCAD.conf config file is now being stored in ~/.config/Unknown Organization/ instead of ~/.config/OpenSCAD/

**To Reproduce**

Observe there's no "Unknown Organization" dir in the .config dir.

19:42:55 ~ > ls -l .config/O* .config/U*
ls: cannot access '.config/U*': No such file or directory
.config/OpenSCAD:
total 8
-rw-r--r-- 1 root root 4023 04-JAN-2026 09:49:48am EST OpenSCAD.conf

Open a file in the latest nightly build:

19:45:31 ~ > openscad-nightly 3D_printer/my_designs/angle_gauges/angle_gauges.scad

Observe that it has none of my custom settings, and is in the default configuration. Close it.

Observe that there's now a "Unknown Organization" dir with a new openscad-nightly.conf file in it.

19:47:07 ~ > ls -l .config/O* .config/U*
.config/OpenSCAD:
total 8
-rw-r--r-- 1 root root 4023 04-JAN-2026 09:49:48am EST OpenSCAD.conf
'.config/Unknown Organization':
total 4
-rw-r--r-- 1 root root 338 14-JAN-2026 07:46:26pm EST openscad-nightly.conf

**Expected behavior**
The configuration/preferences file should be called OpenSCAD.conf, and stored in the OpenSCAD config directory.

**Code reproducing the issue**
N/A

**Screenshots**
N/A

**Environment and Version info (please complete the following information):**
OS is Devuan Freia (Linux)

OpenSCAD version 2026.01.14.nightly (git e779288) installed from the Debian package on download.opensuse.org

**Library & Graphics card information**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by kintel**
Fixes #6528

### CODE REVIEW

File: src/gui/OpenSCADApp.cc [hunk 1]
```diff
@@ -26,9 +25,6 @@ OpenSCADApp::OpenSCADApp(int& argc, char **argv) : QApplication(argc, argv)
 #ifdef Q_OS_MACOS
   this->installEventFilter(new SCADEventFilter(this));
 #endif
```
Comment (coryrc) [inline src/gui/OpenSCADApp.cc:27]: Could you leave a comment here warning not to add ... anything? anything referencing settings or preferences in any way? ... to this section? Or maybe "consider #6528 and #6533 before adding anything here"?

Comment (kintel) [reply src/gui/OpenSCADApp.cc:27]: done
