### PR TITLE
Don't attempt to dereference a null QOpenGLContext

### LINKED ISSUE #6746: OpenSCAD nightly crashes frequently on Windows right-click
**Describe the bug**
OpenSCAD GUI disappears.

**To Reproduce**
1. Run OpenSCAD on Windows
2. Load a .scad file [being edited in an external editor (CLion) -- probably not relevant to the problem]
3. Right-click and drag to pan view
4. Very frequently crash occurs

**Expected behavior**
Continue working.

**Environment and Version info (please complete the following information):**

Processor	13th Gen Intel(R) Core(TM) i7-13850HX   2.10 GHz
Installed RAM	32.0 GB (31.7 GB usable)
Storage	477 GB SSD NVMe PC811 SK hynix 512GB
Graphics Card	NVIDIA RTX 2000 Ada Generation Laptop GPU (8 GB), Intel(R) UHD Graphics (128 MB)
System Type	64-bit operating system, x64-based processor

Edition	Windows 10 Pro
Version	22H2
Installed on	‎12/‎15/‎2024
OS Build	19045.6466

**Library & Graphics card information**

OpenSCAD Version: 2026.03.28 (git 10b32af0)
System information: Microsoft Windows 10 (10.0.19045) x86_64 28 CPUs 31.69 GB RAM
User Agent: OpenSCAD/2026.03.28 (git 10b32af0) (Microsoft Windows 10 (10.0.19045) x86_64)
Compiler: GCC "14.3.0" 64bit
MinGW build: MingW64
Debug build: No
Boost version: 1_85
Eigen version: 3.4.0
CGAL version, kernels: 6.1, Cartesian<Gmpq>, Extended_cartesian<Gmpq>
OpenCSG version: OpenCSG 1.5.0
Clipper2 version: 2.0.1
Manifold version: 3.4.0
Qt version: 6.10.1
QScintilla version: 2.14.1
InputDrivers: 
GLib version: 2.87.1
lodepng version: 20260102
libzip version: 1.5.2
fontconfig version: 2.16.0
freetype version: 2.14.1
harfbuzz version: 12.2.0
cairo version: 1.18.4
lib3mf version: 1.8.1

Features: roof, input-driver-dbus, lazy-union, vertex-object-renderers-indexing, textmetrics*, import-function, object-function, predictible-output, vector-swizzle, discretization-by-error
Application Path: C:/software/OpenSCAD
Documents Path: C:\Users\dstine\Documents
User Documents Path: C:\Users\dstine\Documents
Resource Path: C:/software/OpenSCAD
User Library Path: C:/Users/dstine/Documents/OpenSCAD/libraries
User Examples Path: C:/Users/dstine/Documents/OpenSCAD/examples
User Config Path: C:\Users\dstine\AppData\Local/OpenSCAD
Backup Path: C:/Users/dstine/Documents/OpenSCAD/backups
OPENSCADPATH: <not set>
OpenSCAD library path:
C:/Users/dstine/Documents/OpenSCAD/libraries
C:/software/OpenSCAD\libraries

OPENSCAD_FONT_PATH: <not set>
OpenSCAD font path:
C:/Windows/fonts
C:/Users/dstine/AppData/Local/Microsoft/Windows/Fonts
C:/Users/dstine/.local/share/fonts
C:/usr/local/share/fonts
C:/usr/share/fonts
C:/usr/X11/lib/X11/fonts
C:/System/Library/Fonts
C:/Library/Fonts
C:/Users/dstine/Library/Fonts
GLEW version: 2.1.0
OpenGL Version: 4.6.0 - Build 32.0.101.7077
GL Renderer: Intel(R) RaptorLake-S Mobile Graphics Controller
GL Vendor: Intel
RGBA(8888), depth(24), stencil(8)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes

Qt graphics widget: QOpenGLWidget
QSurfaceFormat: RGBA(8888), depth(24), stencil(8)

GL Extensions:
GL_3DFX_texture_compression_FXT1
GL_AMD_depth_clamp_separate
GL_AMD_vertex_shader_layer
GL_AMD_vertex_shader_viewport_index
GL_ARB_ES2_compatibility
GL_ARB_ES3_1_compatibility
GL_ARB_ES3_compatibility
GL_ARB_arrays_of_arrays
GL_ARB_base_instance
GL_ARB_bindless_texture
GL_ARB_blend_func_extended
GL_ARB_buffer_storage
GL_ARB_cl_event
GL_ARB_clear_buffer_object
GL_ARB_clear_texture
GL_ARB_clip_control
GL_ARB_color_buffer_float
GL_ARB_compatibility
GL_ARB_compressed_texture_pixel_storage
GL_ARB_compute_shader
GL_ARB_conditional_render_inverted
GL_ARB_conservative_depth
GL_ARB_copy_buffer
GL_ARB_copy_image
GL_ARB_cull_distance
GL_ARB_debug_output
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_derivative_control
GL_ARB_direct_state_access
GL_ARB_draw_buffers
GL_ARB_draw_buffers_blend
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_indirect
GL_ARB_draw_instanced
GL_ARB_enhanced_layouts
GL_ARB_explicit_attrib_location
GL_ARB_explicit_uniform_location
GL_ARB_fragment_coord_conventions
GL_ARB_fragment_layer_viewport
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_fragment_shader_interlock
GL_ARB_framebuffer_no_attachments
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_geometry_shader4
GL_ARB_get_program_binary
GL_ARB_get_texture_sub_image
GL_ARB_gl_spirv
GL_ARB_gpu_shader5
GL_ARB_gpu_shader_fp64
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_indirect_parameters
GL_ARB_instanced_arrays
GL_ARB_internalformat_query
GL_ARB_internalformat_query2
GL_ARB_invalidate_subdata
GL_ARB_map_buffer_alignment
GL_ARB_map_buffer_range
GL_ARB_multi_bind
GL_ARB_multi_draw_indirect
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_occlusion_query2
GL_ARB_pipeline_statistics_query
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_polygon_offset_clamp
GL_ARB_post_depth_coverage
GL_ARB_program_interface_query
GL_ARB_provoking_vertex
GL_ARB_query_buffer_object
GL_ARB_robust_buffer_access_behavior
GL_ARB_robustness
GL_ARB_robustness_isolation
GL_ARB_sample_shading
GL_ARB_sampler_objects
GL_ARB_seamless_cube_map
GL_ARB_seamless_cubemap_per_texture
GL_ARB_separate_shader_objects
GL_ARB_shader_atomic_counter_ops
GL_ARB_shader_atomic_counters
GL_ARB_shader_bit_encoding
GL_ARB_shader_draw_parameters
GL_ARB_shader_group_vote
GL_ARB_shader_image_load_store
GL_ARB_shader_image_size
GL_ARB_shader_objects
GL_ARB_shader_precision
GL_ARB_shader_stencil_export
GL_ARB_shader_storage_buffer_object
GL_ARB_shader_subroutine
GL_ARB_shader_texture_image_samples
GL_ARB_shader_texture_lod
GL_ARB_shading_language_100
GL_ARB_shading_language_420pack
GL_ARB_shading_language_packing
GL_ARB_shadow
GL_ARB_spirv_extensions
GL_ARB_stencil_texturing
GL_ARB_sync
GL_ARB_tessellation_shader
GL_ARB_texture_barrier
GL_ARB_texture_border_clamp
GL_ARB_texture_buffer_object
GL_ARB_texture_buffer_object_rgb32
GL_ARB_texture_buffer_range
GL_ARB_texture_compression
GL_ARB_texture_compression_bptc
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_cube_map_array
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_crossbar
GL_ARB_texture_env_dot3
GL_ARB_texture_filter_anisotropic
GL_ARB_texture_float
GL_ARB_texture_gather
GL_ARB_texture_mirror_clamp_to_edge
GL_ARB_texture_mirrored_repeat
GL_ARB_texture_multisample
GL_ARB_texture_non_power_of_two
GL_ARB_texture_query_levels
GL_ARB_texture_query_lod
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui
GL_ARB_texture_stencil8
GL_ARB_texture_storage
GL_ARB_texture_storage_multisample
GL_ARB_texture_swizzle
GL_ARB_texture_view
GL_ARB_timer_query
GL_ARB_transform_feedback2
GL_ARB_transform_feedback3
GL_ARB_transform_feedback_instanced
GL_ARB_transform_feedback_overflow_query
GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object
GL_ARB_vertex_array_bgra
GL_ARB_vertex_array_object
GL_ARB_vertex_attrib_64bit
GL_ARB_vertex_attrib_binding
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_vertex_type_10f_11f_11f_rev
GL_ARB_vertex_type_2_10_10_10_rev
GL_ARB_viewport_array
GL_ARB_window_pos
GL_ATI_meminfo
GL_ATI_separate_stencil
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_clip_volume_hint
GL_EXT_compiled_vertex_array
GL_EXT_depth_bounds_test
GL_EXT_direct_state_access
GL_EXT_draw_buffers2
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXT_framebuffer_object
GL_EXT_geometry_shader4
GL_EXT_gpu_program_parameters
GL_EXT_gpu_shader4
GL_EXT_memory_object
GL_EXT_memory_object_win32
GL_EXT_multi_draw_arrays
GL_EXT_packed_depth_stencil
GL_EXT_packed_float
GL_EXT_packed_pixels
GL_EXT_polygon_offset_clamp
GL_EXT_rescale_normal
GL_EXT_secondary_color
GL_EXT_semaphore
GL_EXT_semaphore_win32
GL_EXT_separate_specular_color
GL_EXT_shader_framebuffer_fetch
GL_EXT_shader_integer_mix
GL_EXT_shadow_funcs
GL_EXT_stencil_two_side
GL_EXT_stencil_wrap
GL_EXT_texture3D
GL_EXT_texture_array
GL_EXT_texture_compression_s3tc
GL_EXT_texture_edge_clamp
GL_EXT_texture_env_add
GL_EXT_texture_env_combine
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_integer
GL_EXT_texture_lod_bias
GL_EXT_texture_rectangle
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_decode
GL_EXT_texture_shared_exponent
GL_EXT_texture_snorm
GL_EXT_texture_storage
GL_EXT_texture_swizzle
GL_EXT_timer_query
GL_EXT_transform_feedback
GL_IBM_texture_mirrored_repeat
GL_INTEL_conservative_rasterization
GL_INTEL_fragment_shader_ordering
GL_INTEL_framebuffer_CMAA
GL_INTEL_map_texture
GL_INTEL_multi_rate_fragment_shader
GL_INTEL_performance_query
GL_KHR_blend_equation_advanced
GL_KHR_blend_equation_advanced_coherent
GL_KHR_context_flush_control
GL_KHR_debug
GL_KHR_no_error
GL_KHR_shader_subgroup
GL_KHR_shader_subgroup_arithmetic
GL_KHR_shader_subgroup_ballot
GL_KHR_shader_subgroup_basic
GL_KHR_shader_subgroup_clustered
GL_KHR_shader_subgroup_quad
GL_KHR_shader_subgroup_shuffle
GL_KHR_shader_subgroup_shuffle_relative
GL_KHR_shader_subgroup_vote
GL_KHR_texture_compression_astc_ldr
GL_NV_blend_square
GL_NV_conditional_render
GL_NV_primitive_restart
GL_NV_texgen_reflection
GL_NV_timeline_semaphore
GL_OVR_multiview
GL_SGIS_generate_mipmap
GL_SGIS_texture_edge_clamp
GL_SGIS_texture_lod
GL_SUN_multi_draw_arrays
GL_WIN_swap_hint
WGL_EXT_swap_control

**Additional context**
Tried various nightlies from Feb and Mar.  Couldn't find one that doesn't crash.

### PR DESCRIPTION
**Pull request by kintel**
Fixes #6746

### CODE REVIEW

File: src/gui/QGLView2.cc [hunk 1]
```diff
@@ -47,5 +47,7 @@ void setGLContext(QOpenGLContext *ctx)
    * Why isn't there a QOpenGLContext::makeCurrent() that uses the context's assigned
    * surface?
    */
-  ctx->makeCurrent(ctx->surface());
+  if (ctx) {
+    ctx->makeCurrent(ctx->surface());
+  }
```
Comment (jordanbrown0) [inline src/gui/QGLView2.cc:52]: Well, maybe, but is anybody supposed to call this with nullptr?  What does it mean?  Are you sure that there isn't a problem with the caller?

Comment (kintel) [reply src/gui/QGLView2.cc:52]: I believe the root cause is that mouse events are issued without there necessarily being an active GL context. The caller creates its own context, then try to restore the previous context. But if the previous context wasn't active (nullptr), there is nothing to restore.

Comment (jordanbrown0) [reply src/gui/QGLView2.cc:52]: In that case, should it (somehow, not obvious how given the API) restore the no-context-selected state?

Comment (jordanbrown0) [reply src/gui/QGLView2.cc:52]: Note also:  at least for me, this problem only happens with a flurry of clicks.  A single double-click does not usually cause it, suggesting that it's not as simple as "there is no context when you double-click".  It sounds like there's somehow a window in the flurry of double-clicks where there is temporarily no context.

Comment (kintel) [reply src/gui/QGLView2.cc:52]: Good point, since we call makeCurrent(), we should probably call doneCurrent().
..then restore the existing context if applicable.

I'm not sure exactly what is going on. I have a feeling the whole render-on-mouse-click approach should be rewritten by someone who really understands how this behaves across platforms..

Comment (jordanbrown0) [reply src/gui/QGLView2.cc:52]: The behavior (happens only on a flurry) smells to me like a race.  Does Qt process events in more than one thread?  Assuming not, is there another thread that's mucking with this same data structure?

Comment (kintel) [reply src/gui/QGLView2.cc:52]: I believe Qt's event loop is single-threaded, but a current GL context may possibly survive multiple events. I kind of lost overview over how Qt works sometime between Qt5 and Qt6..
